/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Supplier;

import DBconnection.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Timansi_Lakshika
 */
public class CustormizeOrders extends javax.swing.JInternalFrame {
    
    Connection conn1 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    PreparedStatement pst4 = null;
    PreparedStatement pst5 = null;
    PreparedStatement pst6 = null;
    PreparedStatement pst7 = null;
    PreparedStatement pst8 = null;
    PreparedStatement pst9 = null;
    PreparedStatement pst10 = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    ResultSet rs4 = null;
    ResultSet rs5 = null;
    ResultSet rs6 = null;

    /**
     * Creates new form CutomermizeOrders
     */
    public CustormizeOrders() {
        initComponents();
        conn1 = DBconnect.connectDb();
        LoadingCustomizedOrderTable();
        TextTotal.setEditable(false);
        jButton1.setEnabled(false);
        jButton4.setEnabled(false);
        
    }
    
    void LoadingCustomizedOrderTable(){
        String sql = "SELECT * FROM CustomizedOrders";
        
        try {
            pst1 = conn1.prepareStatement(sql);
            rs1 = pst1.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            
            
        } 
        catch (SQLException e) {
            //Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,e);
        }finally{
            try {
                pst1.close();
                rs1.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    void LoadingCustomizedOrderItemsTable(){
        try {
            int id = Integer.parseInt(LabelOID.getText());
            
            String sql = "SELECT ItemCode,Quantity,Price FROM CustomizedOrderItems WHERE OrderID = '"+id+"'";
            pst2 = conn1.prepareStatement(sql);
            rs2 = pst2.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs2));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                pst2.close();
                rs2.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void ClearSupplierOrderWindow(){
        LabelOID.setText("");
        TextSID.setText("");
        BoxOrderStatus.setSelectedItem("");
        BoxPaymentStatus.setSelectedItem("");
        TextStartDate.setText("");
        TextEndDate.setText("");
        TextTotal.setText("");
    }
    
    public void ClearCustomizedOrderItems(){
        TextItemID.setText("");
        /*TextItemName.setText("");
        TextBrandID.setText("");
        TextBrandName.setText("");*/
        TextQuantity.setText("");
        TextPrice.setText("");
        TextPriceTotal.setText("");
    }
    
    public boolean isValidPhone(String phone){
       
        //Validating Phone Text Field
        if(phone.length()==10){
            for(int i=0;i<10;i++){
                if(Character.isLetter(phone.charAt(i))){
                    JOptionPane.showMessageDialog(null,"Please Enter a Valid Telephone Number. (Enter digits only)!","Error!", JOptionPane.INFORMATION_MESSAGE);
                    return false;
                }
            } 
        }
        else if(phone.length()!=10){
            JOptionPane.showMessageDialog(null,"Please Enter a Valid Telephone Number with exact 10 digits!","Error!", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        return true;
       //Phone Validation Ends
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TextQuantity = new javax.swing.JTextField();
        TextPriceTotal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        OrderID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TextPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextItemID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CustomerID = new javax.swing.JLabel();
        calculateTotal = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextEndDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextStartDate = new javax.swing.JTextField();
        TextTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextCID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextSID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BoxOrderStatus = new javax.swing.JComboBox<>();
        BoxPaymentStatus = new javax.swing.JComboBox<>();
        LabelOID = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SearchCustomerOrder = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RefreshCustomerOrderTable = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Demo = new javax.swing.JButton();

        jDialog1.setPreferredSize(new java.awt.Dimension(1052, 540));
        jDialog1.setSize(new java.awt.Dimension(1052, 540));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Code", "Qunantity", "Price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Price");

        TextQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextQuantityKeyTyped(evt);
            }
        });

        TextPriceTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total   = ");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        OrderID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Item Code");

        TextPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextPriceKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Order ID");

        TextItemID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Qunatity");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Customer ID");

        CustomerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        calculateTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculateTotal.setText("Calculate Total");
        calculateTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTotalActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(91, 91, 91)
                        .addComponent(OrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(66, 66, 66)
                        .addComponent(CustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(78, 78, 78)
                        .addComponent(TextItemID))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextQuantity)
                            .addComponent(TextPrice)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(TextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TextItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(ClearButton))
                .addGap(28, 28, 28)
                .addComponent(calculateTotal)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Demo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1660, 1000));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "SupplierID", "Order Status", "Payment Status", "Start Date", "End Date", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("OrderID");

        TextEndDate.setEditable(false);
        TextEndDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("End Date");

        TextStartDate.setEditable(false);
        TextStartDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextTotal.setEditable(false);
        TextTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Order Status");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CustomerID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total Amount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Payment Status");

        TextCID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextCID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCIDKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Start Date");

        TextSID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextSIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SupplierID");

        BoxOrderStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Varified", "Delivered" }));

        BoxPaymentStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BoxPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Completed", "Completed" }));

        LabelOID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("New Entry");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextCID, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(TextSID)
                    .addComponent(LabelOID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextTotal)
                    .addComponent(BoxOrderStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxPaymentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextStartDate)
                    .addComponent(TextEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(LabelOID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(TextCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(BoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TextEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TextSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(BoxPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 78, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Update Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Delete Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Add Items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(38, 38, 38)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(Clear)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        SearchCustomerOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchCustomerOrder.setText("Search");
        SearchCustomerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerOrderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Customer  Order ID:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        RefreshCustomerOrderTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RefreshCustomerOrderTable.setText("Refresh");
        RefreshCustomerOrderTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshCustomerOrderTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchCustomerOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(RefreshCustomerOrderTable)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCustomerOrder)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshCustomerOrderTable))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setFocusCycleRoot(true);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Customized Orders");

        Demo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Demo.setText("Demo");
        Demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Demo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Demo))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
            int oid = Integer.parseInt(LabelOID.getText());
            int cid = Integer.parseInt(TextCID.getText());
            String cid1 = TextCID.getText();
            int sid = Integer.parseInt(TextSID.getText());
            String oStatus  = BoxOrderStatus.getSelectedItem().toString();
            String pStatus  = BoxPaymentStatus.getSelectedItem().toString();
            String startDate = TextStartDate.getText();
            String endDate = TextEndDate.getText();
            Double total = Double.parseDouble(TextTotal.getText());
            //double total = 0;
            //TextTotal.setText(Double.toString(total));
            //total = Double.parseDouble(TextTotal.getText());
            if(isValidPhone(cid1)==true){
            
        try {
    
            
            String sql2 = "INSERT INTO CustomizedOrders (OrderID, CustomerID, SupplierID, OrderStatus, PaymentStatus, StartDate, EndDate, Total) VALUES ('"+oid+"','"+cid+"','"+sid+"','"+oStatus+"','"+pStatus+"','"+startDate+"','"+endDate+"','"+total+"') ";
            
            pst3 = conn1.prepareStatement(sql2);
            pst3.execute();
            
            LoadingCustomizedOrderTable();
            JOptionPane.showMessageDialog(null,"Order successfully placed!","Order Placed", JOptionPane.INFORMATION_MESSAGE);
            
            LabelOID.setText("");
            TextCID.setText("");
            TextSID.setText("");
            BoxOrderStatus.setSelectedItem("");
            BoxPaymentStatus.setSelectedItem("");
            TextStartDate.setText("");
            TextEndDate.setText("");
            TextTotal.setText("");
            
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error in placing the order!","Error", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,ex);
            
        } finally{
            try {
                pst3.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(LabelOID.getText().equals("") || TextCID.getText().equals("") || TextSID.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Enter the CustomerID and SupplierID before Adding Items!","Error!", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        jDialog1.setVisible (true);
        OrderID.setText(LabelOID.getText());
        CustomerID.setText(TextCID.getText());
        LoadingCustomizedOrderItemsTable();
        ClearCustomizedOrderItems();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(LabelOID.getText().equals("")){
            //JOptionPane.showMessageDialog(null,"No record Has been selected to update!");
            JOptionPane.showMessageDialog(null,"No record has been selected to update!","Error!", JOptionPane.INFORMATION_MESSAGE);

        }
        else{
        
        int x = JOptionPane.showConfirmDialog(null,"Want to Update?");
        
        if(x==0){
        
        int oid = Integer.parseInt(LabelOID.getText());
        int cid = Integer.parseInt(TextCID.getText());
        int sid = Integer.parseInt(TextSID.getText());
        String oStatus  = BoxOrderStatus.getSelectedItem().toString();
        String pStatus  = BoxPaymentStatus.getSelectedItem().toString();
        String startDate = TextStartDate.getText();
        String endDate = TextEndDate.getText();
        Double total = Double.parseDouble(TextTotal.getText());
        
        try{  
            String sql1 = "UPDATE CustomizedOrders SET OrderID = '"+oid+"',CustomerID = '"+cid+"', SupplierID = '"+sid+"',OrderStatus = '"+oStatus+"',PaymentStatus = '"+pStatus+"', StartDate = '"+startDate+"',EndDate = '"+endDate+"',Total = '"+total+"' WHERE OrderID = '"+oid+"' ";
            pst4 = conn1.prepareStatement(sql1);
            pst4.execute();
            
            LoadingCustomizedOrderTable();
            
           
        }
        catch(Exception e){
            //JOptionPane.showConfirmDialog(null,e);
            JOptionPane.showMessageDialog(null,"Error in updating the record!","Error!", JOptionPane.INFORMATION_MESSAGE);
        }finally{
            try {
                pst4.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
        
        LabelOID.setText("");
        TextCID.setText("");
        TextSID.setText("");
        BoxOrderStatus.setSelectedItem("");
        BoxPaymentStatus.setSelectedItem("");
        TextStartDate.setText("");
        TextEndDate.setText("");
        TextTotal.setText("");
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this record?");

        if(x==0)

        {

            String OID = LabelOID.getText();

            try {
                String sql1 = "DELETE from CustomizedOrders WHERE OrderID = '"+OID+"'";
                
                pst5 = conn1.prepareStatement(sql1);
                pst5.execute();
               

                //load the table after deleting the record
                LoadingCustomizedOrderTable();
                
                }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            } finally{
                try {
                    pst5.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            LabelOID.setText("");
            TextCID.setText("");
            TextSID.setText("");
            BoxOrderStatus.setSelectedItem("");
            BoxPaymentStatus.setSelectedItem("");
            TextStartDate.setText("");
            TextEndDate.setText("");
            TextTotal.setText("");
        }
    }                                                                          

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jButton4.setEnabled(true);
        jButton1.setEnabled(false);
        int row=jTable1.getSelectedRow();
       
       String oid=jTable1.getValueAt(row,0).toString();
       String cid=jTable1.getValueAt(row,1).toString();
       String sid=jTable1.getValueAt(row,2).toString();
       String oStatus=jTable1.getValueAt(row,3).toString();
       String pStatus=jTable1.getValueAt(row,4).toString();
       String startDate=jTable1.getValueAt(row,5).toString();
       String endDate=jTable1.getValueAt(row,6).toString();
       String total=jTable1.getValueAt(row,7).toString();
       
       
       LabelOID.setText(oid);
       //LabelOID.setEditable(false);
       TextCID.setText(cid);
       TextSID.setText(sid);
       BoxOrderStatus.setSelectedItem(oStatus);
       BoxPaymentStatus.setSelectedItem(pStatus);
       TextStartDate.setText(startDate);
       TextEndDate.setText(endDate);
       TextTotal.setText(total);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        LocalDate today = LocalDate.now();
        TextStartDate.setText(today.toString());
        
        jButton4.setEnabled(true);
        try {
            
            String sql = "SELECT * FROM CustomizedOrders";
            pst6 = conn1.prepareStatement(sql);
            rs3 = pst6.executeQuery();
            
            int row = -1;
            
            while(rs3.next()){
                row++;
            }
            
            if(row==-1){
                LabelOID.setText(String.valueOf("1"));
            }
            else{
                String oid=jTable1.getValueAt(row,0).toString();
                int oid1 = Integer.parseInt(oid);
                int OID = oid1 + 1;
                LabelOID.setText(String.valueOf(OID));
            }
            ClearCustomizedOrderItems();
            
        } catch (SQLException ex) {
            Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                pst6.close();
                rs3.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        //}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            String ioid = OrderID.getText();
            String cid = CustomerID.getText();
            String iid = TextItemID.getText();
            /*String name = TextItemName.getText();
            String bid = TextBrandID.getText();
            String bname = TextBrandName.getText();*/
            String qnty = TextQuantity.getText();
            
            double price = Double.parseDouble(TextPrice.getText());
        
            try {    
                //String s1 = "INSERT INTO CustomizedOrderItems (OrderID,CustomerID,ItemCode,ItemName,BrandID,BrandName,Quantity,Price) VALUES ('"+ioid+"','"+cid+"','"+iid+"','"+name+"','"+bid+"','"+bname+"','"+qnty+"','"+price+"')";
                String s1 = "INSERT INTO CustomizedOrderItems (OrderID,CustomerID,ItemCode,Quantity,Price) VALUES ('"+ioid+"','"+cid+"','"+iid+"','"+qnty+"','"+price+"')";
                pst7 = conn1.prepareStatement(s1);
                pst7.execute();
                
                LoadingCustomizedOrderItemsTable();
                
                JOptionPane.showMessageDialog(null,"Item successfully added!","Added", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (SQLException ex) {
                Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,ex);
            } finally{
                try {
                    pst7.close();
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            /*
            TextItemID.setText("");
            TextItemName.setText("");
            TextBrandID.setText("");
            TextBrandName.setText("");
            TextQuantity.setText("");*/
            
            ClearCustomizedOrderItems();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int x = JOptionPane.showConfirmDialog(null,"Want to Update?");

        if(x==0){
            TextItemID.setEditable(true);

            String ioid = OrderID.getText();
            String iid = TextItemID.getText();
            /*String name = TextItemName.getText();
            String bid = TextBrandID.getText();
            String bname = TextBrandName.getText();*/
            String qnty = TextQuantity.getText();

            double price = Double.parseDouble(TextPrice.getText());

            try {
                //String s3 = "UPDATE CustomizedOrderItems SET OrderID = '"+ioid+"',ItemCode = '"+iid+"',ItemName = '"+name+"',BrandID = '"+bid+"',BrandName = '"+bname+"',Quantity = '"+qnty+"',Price = '"+price+"' WHERE (OrderID = '"+ioid+"' AND ItemCode = '"+iid+"')";
                String s3 = "UPDATE CustomizedOrderItems SET OrderID = '"+ioid+"',ItemCode = '"+iid+"',Quantity = '"+qnty+"',Price = '"+price+"' WHERE (OrderID = '"+ioid+"' AND ItemCode = '"+iid+"')";
                pst9 = conn1.prepareStatement(s3);
                pst9.execute();

                LoadingCustomizedOrderItemsTable();

            } catch (SQLException ex) {
                Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    pst9.close();
                    ClearCustomizedOrderItems();
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void calculateTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTotalActionPerformed
        jButton1.setEnabled(true);
        try {
            // TODO add your handling code here:
            int ioid = Integer.parseInt(OrderID.getText());
            String s2 = "SELECT * FROM CustomizedOrderItems WHERE OrderID = '"+ioid+"'";
            pst8 = conn1.prepareStatement(s2);
            rs4 = pst8.executeQuery();
            
            int row = -1;
            double totalPrice = 0;
            while(rs4.next()){
                row++;
                String Price = jTable2.getValueAt(row,2).toString();
                double NewPrice = Double.parseDouble(Price);
                totalPrice = totalPrice + NewPrice;
            }
            TextPriceTotal.setText(Double.toString(totalPrice));
            TextTotal.setText(Double.toString(totalPrice));
            jButton1.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        } finally{
            try {
                pst8.close();
                rs4.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_calculateTotalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TextItemID.setEditable(true);
        
        //Deleting the rocord of added items to the Supplier Order

        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this record?");

        if(x==0)

        {

            String OID = OrderID.getText();
            String iid = TextItemID.getText();
            try {
                String sql1 = "DELETE from SupplierOrderItems WHERE (OrderID = '"+OID+"' AND ItemCode = '"+iid+"')";

                pst7 = conn1.prepareStatement(sql1);
                pst7.execute();

                //load the table after deleting the record
                LoadingCustomizedOrderItemsTable();

            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            } finally{
                try {
                    pst7.close();
                    ClearCustomizedOrderItems();
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        ClearCustomizedOrderItems();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jButton1.setEnabled(false);
        
        int row=jTable2.getSelectedRow();
       
       //String oid=jTable2.getValueAt(row,0).toString();
       //String cid=jTable2.getValueAt(row,1).toString();
       //String sid=jTable2.getValueAt(row,2).toString();
       /*String ICode=jTable2.getValueAt(row,3).toString();
       String IName=jTable2.getValueAt(row,4).toString();
       String BID=jTable2.getValueAt(row,5).toString();
       String Bname=jTable2.getValueAt(row,6).toString();
       String qnty=jTable2.getValueAt(row,7).toString();
       String price=jTable2.getValueAt(row,8).toString();*/
       String ICode=jTable2.getValueAt(row,0).toString();
       /*String IName=jTable2.getValueAt(row,1).toString();
       String BID=jTable2.getValueAt(row,2).toString();
       String Bname=jTable2.getValueAt(row,3).toString();*/
       String qnty=jTable2.getValueAt(row,1).toString();
       String price=jTable2.getValueAt(row,2).toString();
       
       
       //OrderID.setText(oid);
       //CustomerID.setText(cid);
       //TextSID.setText(sid);
       TextItemID.setText(ICode);
       /*TextItemName.setText(IName);
       TextBrandID.setText(BID);
       TextBrandName.setText(Bname);*/
       TextQuantity.setText(qnty);
       TextPrice.setText(price);
       TextPriceTotal.setText("");
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void TextSIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextSIDKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextSIDKeyTyped

    private void TextCIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCIDKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
        
        String check = TextCID.getText()+c;
        
        if(check.length()>10){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Only ten numbers are allowed!");
        }
    }//GEN-LAST:event_TextCIDKeyTyped

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       LabelOID.setText("");
       TextCID.setText("");
       TextSID.setText("");
       TextTotal.setText("");
       BoxOrderStatus.setSelectedItem("");
       BoxPaymentStatus.setSelectedItem("");
       TextStartDate.setText("");
       TextEndDate.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void TextQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextQuantityKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextQuantityKeyTyped

    private void TextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPriceKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextPriceKeyTyped

    private void SearchCustomerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerOrderActionPerformed
        try {
            String str1 = "SELECT * FROM CustomizedOrders WHERE OrderID='"+jTextField1.getText()+"'";
            pst3 = conn1.prepareStatement(str1);
            rs2 = pst3.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs2));
        } catch (SQLException ex) {
            Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                pst3.close();
                rs2.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_SearchCustomerOrderActionPerformed

    private void RefreshCustomerOrderTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshCustomerOrderTableActionPerformed
        // TODO add your handling code here:
        LoadingCustomizedOrderTable();
    }//GEN-LAST:event_RefreshCustomerOrderTableActionPerformed

    private void DemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoActionPerformed
       //LabelOID.setText("");
       TextCID.setText("0712226665");
       TextSID.setText("23");
       //TextTotal.setText("");
       BoxOrderStatus.setSelectedItem("Pending");
       BoxPaymentStatus.setSelectedItem("Not Completed");
       //TextStartDate.setText("");
       //TextEndDate.setText("");
    }//GEN-LAST:event_DemoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        TextItemID.setText("PNT001");
        TextQuantity.setText("100");
        TextPrice.setText("200000");
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxOrderStatus;
    private javax.swing.JComboBox<String> BoxPaymentStatus;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JButton Demo;
    private javax.swing.JLabel LabelOID;
    private javax.swing.JLabel OrderID;
    private javax.swing.JButton RefreshCustomerOrderTable;
    private javax.swing.JButton SearchCustomerOrder;
    private javax.swing.JTextField TextCID;
    private javax.swing.JTextField TextEndDate;
    private javax.swing.JTextField TextItemID;
    private javax.swing.JTextField TextPrice;
    private javax.swing.JTextField TextPriceTotal;
    private javax.swing.JTextField TextQuantity;
    private javax.swing.JTextField TextSID;
    private javax.swing.JTextField TextStartDate;
    private javax.swing.JTextField TextTotal;
    private javax.swing.JButton calculateTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
