/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Supplier;

import DBconnection.DBconnect;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.time.LocalDate;

/**
 *
 * @author Timansi_Lakshika
 */
public class SupplierOrders extends javax.swing.JInternalFrame {
    
    Connection conn1 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    PreparedStatement pst4 = null;
    PreparedStatement pst5 = null;
    PreparedStatement pst6 = null;
    PreparedStatement pst7 = null;
    PreparedStatement pst8 = null;
    PreparedStatement pst9 = null;
    PreparedStatement pst10 = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    ResultSet rs4 = null;
    ResultSet rs5 = null;

    /**
     * Creates new form SupplierOrders
     */
    public SupplierOrders() {
        initComponents();
        conn1 = DBconnect.connectDb();
        LoadingSupplierOrdersTable();
        TextTotal.setEditable(false);
        jButton1.setEnabled(false);
        jButton4.setEnabled(false);
        TextEndDate.setEditable(true);
        
    }
    
    void LoadingSupplierOrdersTable(){
        String sql = "SELECT * FROM SupplierOrder";
        
        try {
            pst1 = conn1.prepareStatement(sql);
            rs1 = pst1.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            
            
        } 
        catch (SQLException e) {
            //Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"Error in loading the Supplier Details Table!","Error", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    void LoadingSupplierOrderItemsTable(){
        try {
            int id = Integer.parseInt(LableOID.getText());
            
            String sql = "SELECT ItemCode,ItemName,BrandID,BrandName,Quantity,Price FROM SupplierOrderItems WHERE OrderID = '"+id+"'";
            pst2 = conn1.prepareStatement(sql);
            rs2 = pst2.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs2));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ClearSupplierOrderWindow(){
        //jButton1.setEnabled(false);
        //jButton4.setEnabled(false);
        
        LableOID.setText("");
        TextSID.setText("");
        BoxOrderStatus.setSelectedItem("");
        BoxPaymentStatus.setSelectedItem("");
        TextStartDate.setText("");
        TextEndDate.setText("");
        TextTotal.setText("");
    }
    
    public void ClearSupplierOrderItems(){
        
        TextItemID.setText("");
        TextItemName.setText("");
        TextBrandID.setText("");
        TextBrandName.setText("");
        TextQuantity.setText("");
        TextPrice.setText("");
    }
    
    //Validating the Date
    public boolean isDateValid(String Date,String format){
        if(Date==null){
            return false;
        }
        SimpleDateFormat frmt = new SimpleDateFormat(format);
        frmt.setLenient(false);
        
        try{
            java.util.Date date = frmt.parse(Date);
        }
        catch(Exception e){
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TextBrandID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        TextItemName = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        TextBrandName = new javax.swing.JTextField();
        TextPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TextQuantity = new javax.swing.JTextField();
        TextItemID = new javax.swing.JTextField();
        TextPriceTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        OrderID = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextEndDate = new javax.swing.JTextField();
        TextTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        TextSID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BoxOrderStatus = new javax.swing.JComboBox<>();
        BoxPaymentStatus = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        TextStartDate = new javax.swing.JTextField();
        LableOID = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        jDialog1.setSize(new java.awt.Dimension(1141, 667));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Item Code", "Item Name", "BrandID", "Brand Name", "Quantity", "Price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Item Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Brand Name");

        TextBrandID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("OrderID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total = ");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TextItemName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Calculate Total");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        TextBrandName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextPriceKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ItemID");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Price");

        TextQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextQuantityKeyTyped(evt);
            }
        });

        TextItemID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextPriceTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("BrandID");

        OrderID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("Clear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15)
                                .addGap(66, 66, 66)
                                .addComponent(OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton8)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextBrandName)
                                            .addComponent(TextBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextPrice)
                                            .addComponent(TextQuantity)
                                            .addComponent(TextItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(OrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TextBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TextBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1660, 1000));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "SupplierID", "Order Status", "Payment Status", "Start Date", "End Date", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setForeground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("OrderID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SupplierID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total Amount");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Order Status");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Start Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("End Date");

        TextEndDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEndDateActionPerformed(evt);
            }
        });

        TextTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTotalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Insert Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Update Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Remove Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Add Items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TextSID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSIDActionPerformed(evt);
            }
        });
        TextSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextSIDKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Payment Status");

        BoxOrderStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Varified", "Delivered" }));

        BoxPaymentStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BoxPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Completed", "Completed" }));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("New Entry");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        TextStartDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        LableOID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LableOID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextSID)
                    .addComponent(BoxOrderStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxPaymentStatus, 0, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextEndDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(TextTotal)
                    .addComponent(TextStartDate, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addGap(64, 64, 64)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(820, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(371, 371, 371)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableOID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(BoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BoxPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel5)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("   Supplier Orders");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1644, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible (true);
        OrderID.setText(LableOID.getText());
        //OrderID.setEditable(false);
        LoadingSupplierOrderItemsTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            int oid = Integer.parseInt(LableOID.getText());
            String oid1 = LableOID.getText();
            int sid = Integer.parseInt(TextSID.getText());
            String sid1 = TextSID.getText();
            String oStatus  = BoxOrderStatus.getSelectedItem().toString();
            String pStatus  = BoxPaymentStatus.getSelectedItem().toString();
            String startDate = TextStartDate.getText();
            String endDate = TextEndDate.getText();
            Double total = Double.parseDouble(TextTotal.getText());
            String total1 = TextTotal.getText();
            
            if(oid1.equals("") || sid1.equals("") || oStatus.equals("") || pStatus.equals("") || startDate.equals("") || total1.equals("")){
                JOptionPane.showMessageDialog(null,"Except End Date, all the fields should be filled!","Error!", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            
            //Validating the Supplier ID Text Field
            String str = TextSID.getText();
            for(int i=0;i<str.length();i++){
            if(Character.isLetter(str.charAt(i)))
                JOptionPane.showMessageDialog(null,"Please Enter Integer Values For the Supplier ID!","Error!", JOptionPane.INFORMATION_MESSAGE);
            //End of SupplierID Validation
            }
            
            
            //EndDate Validation
            /*if(isDateValid(endDate,"yyyy-MM-dd")==false)
                JOptionPane.showMessageDialog(null,"Please Enter a Valid Date!","Error!", JOptionPane.INFORMATION_MESSAGE);*/
            
            //End of EndDate Validation
            
        try {
            
            String sql1 = "INSERT INTO SupplierOrder (OrderID, SupplierID, OrderStatus, PaymentStatus, StartDate, EndDate, TotalAmount) VALUES ('"+oid+"','"+sid+"','"+oStatus+"','"+pStatus+"','"+startDate+"','"+endDate+"','"+total+"') ";
            //String sql1 = "INSERT INTO SupplierOrder (OrderID, SupplierID, OrderStatus, PaymentStatus, StartDate, TotalAmount) VALUES ('"+oid+"','"+sid+"','"+oStatus+"','"+pStatus+"','"+startDate+"','"+total+"') ";

            pst5 = conn1.prepareStatement(sql1);
            pst5.execute();
            
            LoadingSupplierOrdersTable();
            JOptionPane.showMessageDialog(null,"Order successfully placed!","Order Placed", JOptionPane.INFORMATION_MESSAGE);
            
            /*LableOID.setText("");
            TextSID.setText("");
            TextStartDate.setText("");
            TextEndDate.setText("");
            TextTotal.setText("");*/
            
            ClearSupplierOrderWindow();
            
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null,"Want to Update?");
        
        if(x==0){
        
        int oid = Integer.parseInt(LableOID.getText());
        int sid = Integer.parseInt(TextSID.getText());
        String oStatus  = BoxOrderStatus.getSelectedItem().toString();
        String pStatus  = BoxPaymentStatus.getSelectedItem().toString();
        String startDate = TextStartDate.getText();
        String endDate = TextEndDate.getText();
        Double total = Double.parseDouble(TextTotal.getText());
        
        try{  
            String sql1 = "UPDATE SupplierOrder SET OrderID = '"+oid+"',SupplierID = '"+sid+"',OrderStatus = '"+oStatus+"',PaymentStatus = '"+pStatus+"', StartDate = '"+startDate+"',EndDate = '"+endDate+"',TotalAmount = '"+total+"' WHERE OrderID = '"+oid+"' ";
            //String sql1 = "UPDATE SupplierOrder SET OrderID = '"+oid+"',SupplierID = '"+sid+"',OrderStatus = '"+oStatus+"',PaymentStatus = '"+pStatus+"', StartDate = '"+startDate+"',TotalAmount = '"+total+"' WHERE OrderID = '"+oid+"' ";
            
            pst6 = conn1.prepareStatement(sql1);
            pst6.execute();
            
            LoadingSupplierOrdersTable();
            
           
        }
        catch(Exception e){
            //JOptionPane.showConfirmDialog(null,e);
            //JOptionPane.showMessageDialog(null,"Error in updating the record!","Error!", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,e);
        }
        
        /*LableOID.setText("");
        TextSID.setText("");
        TextStartDate.setText("");
        TextEndDate.setText("");
        TextTotal.setText("");*/
        
        ClearSupplierOrderWindow();
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this record?");

        if(x==0)

        {

            String OID = LableOID.getText();

            try {
                String sql1 = "DELETE from SupplierOrder WHERE OrderID = '"+OID+"'";
                
                pst7 = conn1.prepareStatement(sql1);
                pst7.execute();
               

                //load the table after deleting the record
                LoadingSupplierOrdersTable();
                
                }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            
            ClearSupplierOrderWindow();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       jButton1.setEnabled(false);
       jButton4.setEnabled(true);
       
        
       int row=jTable1.getSelectedRow();
       
       String oid=jTable1.getValueAt(row,0).toString();
       String sid=jTable1.getValueAt(row,1).toString();
       String oStatus=jTable1.getValueAt(row,2).toString();
       String pStatus=jTable1.getValueAt(row,3).toString();
       String startDate=jTable1.getValueAt(row,4).toString();
       String endDate=jTable1.getValueAt(row,5).toString();
       String total=jTable1.getValueAt(row,6).toString();
       
       
       LableOID.setText(oid);
       TextSID.setText(sid);
       BoxOrderStatus.setSelectedItem(oStatus);
       BoxPaymentStatus.setSelectedItem(pStatus);
       TextStartDate.setText(startDate);
       TextEndDate.setText(endDate);
       TextTotal.setText(total);
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ClearSupplierOrderWindow();
        
        jButton4.setEnabled(true);
     
            LocalDate today = LocalDate.now();
            TextStartDate.setText(today.toString());
            TextStartDate.setEditable(false);
            TextTotal.setText("0");
        
        try {
            
            String sql = "SELECT * FROM SupplierOrder";
            pst3 = conn1.prepareStatement(sql);
            rs3 = pst3.executeQuery();
            
            int row = -1;
            
            while(rs3.next()){
                row++;
            }
            
            if(row==-1){
                LableOID.setText(String.valueOf("1"));
            }
            else{
                String oid=jTable1.getValueAt(row,0).toString();
                int oid1 = Integer.parseInt(oid);
                int OID = oid1 + 1;
                LableOID.setText(String.valueOf(OID));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                pst3.close();
                rs3.close();
            } catch (SQLException ex) {
                Logger.getLogger(CustormizeOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        /*LableOID.setText("");
        TextSID.setText("");
        BoxOrderStatus.setSelectedItem("");
        BoxPaymentStatus.setSelectedItem("");
        TextStartDate.setText("");
        TextEndDate.setText("");
        TextTotal.setText("");*/
        
        ClearSupplierOrderWindow();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
        // TODO add your handling code here:
        /*OrderID.setText(LableOID.getText());
        OrderID.setEditable(false);
        LoadingItemsTable();*/
    }//GEN-LAST:event_jDialog1WindowOpened

    private void jDialog1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog1WindowClosing

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        TextItemID.setEditable(false);
        
        int row=jTable2.getSelectedRow();
       
        //String ioid = jTable2.getValueAt(row,0).toString();
        String iid = jTable2.getValueAt(row,0).toString();
        String name = jTable2.getValueAt(row,1).toString();
        String bid = jTable2.getValueAt(row,2).toString();
        String bname = jTable2.getValueAt(row,3).toString();
        int qnty = Integer.parseInt(jTable2.getValueAt(row,4).toString());
        double price = Double.parseDouble(jTable2.getValueAt(row,5).toString());
        //String qnty = jTable2.getValueAt(row,4).toString();
        //String price =jTable2.getValueAt(row,4).toString();
        
        TextItemID.setText(iid);
        TextItemName.setText(name);
        TextBrandID.setText(bid);
        TextBrandName.setText(bname);
        TextQuantity.setText(Integer.toString(qnty));
        TextPrice.setText(Double.toString(price));
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:
        String ioid = OrderID.getText();
        String iid = TextItemID.getText();
        String name = TextItemName.getText();
        String bid = TextBrandID.getText();
        String bname = TextBrandName.getText();
        String qnty = TextQuantity.getText();

        double price = Double.parseDouble(TextPrice.getText());

        try {
            String s1 = "INSERT INTO SupplierOrderItems (OrderID,ItemCode,ItemName,BrandID,BrandName,Quantity,Price) VALUES ('"+ioid+"','"+iid+"','"+name+"','"+bid+"','"+bname+"','"+qnty+"','"+price+"')";
            pst4 = conn1.prepareStatement(s1);
            pst4.execute();

            LoadingSupplierOrderItemsTable();

            JOptionPane.showMessageDialog(null,"Item successfully added!","Added", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,ex);
            JOptionPane.showMessageDialog(null,"Can not Enter two records with same Item number!","Error", JOptionPane.INFORMATION_MESSAGE);
        } finally{
            try {
                pst4.close();
                ClearSupplierOrderItems();
            } catch (SQLException ex) {
                Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(TextSID.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter the Supplier ID before placing the order!","Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        jButton1.setEnabled(true);
        try {
            
            int ioid = Integer.parseInt(OrderID.getText());
            String s2 = "SELECT * FROM SupplierOrderItems WHERE OrderID = '"+ioid+"'";
            pst8 = conn1.prepareStatement(s2);
            rs4 = pst8.executeQuery();

            int row = -1;
            double totalPrice = 0;
            while(rs4.next()){
                row++;
                String Price = jTable2.getValueAt(row,5).toString();
                double NewPrice = Double.parseDouble(Price);
                totalPrice = totalPrice + NewPrice;
            }
            TextPriceTotal.setText(Double.toString(totalPrice));
            TextTotal.setText(Double.toString(totalPrice));
            jButton1.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TextItemID.setEditable(true);
        
        //Deleting the rocord of added items to the Supplier Order

        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this record?");

        if(x==0)

        {

            String OID = OrderID.getText();
            String iid = TextItemID.getText();
            try {
                String sql1 = "DELETE from SupplierOrderItems WHERE (OrderID = '"+OID+"' AND ItemCode = '"+iid+"')";

                pst7 = conn1.prepareStatement(sql1);
                pst7.execute();

                //load the table after deleting the record
                LoadingSupplierOrderItemsTable();

            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            } finally{
                try {
                    pst7.close();
                    ClearSupplierOrderItems();
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Want to Update?");

        if(x==0){
            TextItemID.setEditable(true);

            String ioid = OrderID.getText();
            String iid = TextItemID.getText();
            String name = TextItemName.getText();
            String bid = TextBrandID.getText();
            String bname = TextBrandName.getText();
            String qnty = TextQuantity.getText();

            double price = Double.parseDouble(TextPrice.getText());

            try {
                String s3 = "UPDATE SupplierOrderItems SET OrderID = '"+ioid+"',ItemCode = '"+iid+"',ItemName = '"+name+"',BrandID = '"+bid+"',BrandName = '"+bname+"',Quantity = '"+qnty+"',Price = '"+price+"' WHERE (OrderID = '"+ioid+"' AND ItemCode = '"+iid+"')";
                pst9 = conn1.prepareStatement(s3);
                pst9.execute();

                LoadingSupplierOrderItemsTable();

            } catch (SQLException ex) {
                Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    pst9.close();
                    ClearSupplierOrderItems();
                } catch (SQLException ex) {
                    Logger.getLogger(SupplierOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TextSIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextSIDKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextSIDKeyTyped

    private void TextEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEndDateActionPerformed

    private void TextSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSIDActionPerformed

    private void TextQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextQuantityKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextQuantityKeyTyped

    private void TextPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPriceKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TextPriceKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxOrderStatus;
    private javax.swing.JComboBox<String> BoxPaymentStatus;
    private javax.swing.JLabel LableOID;
    private javax.swing.JLabel OrderID;
    private javax.swing.JTextField TextBrandID;
    private javax.swing.JTextField TextBrandName;
    private javax.swing.JTextField TextEndDate;
    private javax.swing.JTextField TextItemID;
    private javax.swing.JTextField TextItemName;
    private javax.swing.JTextField TextPrice;
    private javax.swing.JTextField TextPriceTotal;
    private javax.swing.JTextField TextQuantity;
    private javax.swing.JTextField TextSID;
    private javax.swing.JTextField TextStartDate;
    private javax.swing.JTextField TextTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
