package Inventory;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damith
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
//import DBClass.conect;
import DBconnection.DBconnect;
import javax.swing.table.TableModel;
import java.text.DateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class ExpireItem extends javax.swing.JInternalFrame {

    Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public ExpireItem() {
        initComponents();
        conn = DBconnect.connectDb();
        tableload();
        tableload1();
        enable();
       
    }

    public void tableload()
    {
        String expire = "select * from  Nearto_Be_Expired";
        try{
        pst = conn.prepareStatement(expire);
        rs = pst.executeQuery();
        
        NearExpire.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
         {
                
         }
        finally
        {
            try{
            pst.close();
            rs.close();
            }
            catch(Exception e){
            
            }
                  
        }
       
    }
    
    public void tableload1()
    {
        String expire1 = "select * from  Expired_Item";
        try{
        pst = conn.prepareStatement(expire1);
        rs = pst.executeQuery();
        
        TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
         {
                
         }
        finally
        {
            try{
            pst.close();
            rs.close();
            }
            catch(Exception e){
            
            }
                  
        }
       
    }
    
    public void tableloadA()
    {
        String dd=((JTextField)FromExpire.getDateEditor().getUiComponent()).getText();
        String dd1=((JTextField)ToExpire.getDateEditor().getUiComponent()).getText();
        //String DDD=()
        
        String sql = "select * from Nearto_Be_Expired where ExpireDate BETWEEN '"+dd+"' AND '"+dd1+"' ";
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        NearExpire.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e){
                
            }    
            finally{
                try{
                pst.close();
                rs.close();
                }
                catch(Exception e)
                {
                    
                }
            }
       
    }
       public void clearExpireItem()
       {
       ESItemID.setText("");
       ESItemName.setText("");
       }
       public void clearExpireBrand()
       {
       ESBrandID.setText("");
       ESBrandName.setText("");
       }
       public void clearExpireSupplier()
       {
       ESSupplierID.setText("");
       ESSupplierName.setText("");
       }
       
       public void enable()
       {
       ESItemID.setEditable(true);
       ESItemName.setEditable(true);
       ESBrandID.setEditable(true);
       ESBrandName.setEditable(true);
       ESSupplierID.setEditable(true);
       ESSupplierName.setEditable(true);
       }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        FromExpire = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        ToExpire = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        NearExpire = new javax.swing.JTable();
        ExpireSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ESSupplierName = new javax.swing.JTextField();
        ESBrandName = new javax.swing.JTextField();
        ESItemName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ESSupplierID = new javax.swing.JTextField();
        ESBrandID = new javax.swing.JTextField();
        ESItemID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ERefesh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableExpire = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel14.setText("From                :");

        FromExpire.setDateFormatString("yyyy-MM-dd");

        jLabel15.setText("To                   :");

        ToExpire.setDateFormatString("yyyy-MM-dd");
        ToExpire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ToExpireKeyReleased(evt);
            }
        });

        NearExpire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(NearExpire);

        ExpireSearch.setText("Search");
        ExpireSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpireSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FromExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ToExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ExpireSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(411, 1125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FromExpire, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ToExpire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExpireSearch))
                .addGap(166, 166, 166)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Near to be expiring", jPanel2);

        ESSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESSupplierNameActionPerformed(evt);
            }
        });
        ESSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESSupplierNameKeyReleased(evt);
            }
        });

        ESBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESBrandNameActionPerformed(evt);
            }
        });
        ESBrandName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESBrandNameKeyReleased(evt);
            }
        });

        ESItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESItemNameActionPerformed(evt);
            }
        });
        ESItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESItemNameKeyReleased(evt);
            }
        });

        jLabel10.setText("Item Name");

        jLabel11.setText("Brand Name");

        jLabel12.setText("Supplier name");

        ESSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESSupplierIDActionPerformed(evt);
            }
        });
        ESSupplierID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESSupplierIDKeyReleased(evt);
            }
        });

        ESBrandID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESBrandIDActionPerformed(evt);
            }
        });
        ESBrandID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESBrandIDKeyReleased(evt);
            }
        });

        ESItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESItemIDActionPerformed(evt);
            }
        });
        ESItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ESItemIDKeyReleased(evt);
            }
        });

        jLabel8.setText("Item ID");

        jLabel7.setText("Brand ID");

        jLabel9.setText("Supplier ID");

        ERefesh.setText("Refesh");
        ERefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERefeshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ESSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ERefesh)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ERefesh))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        TableExpire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableExpire);

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Individual Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1609, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(372, 372, 372))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(103, 103, 103)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Expired Item", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ESItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESItemIDActionPerformed
    ESBrandID.setVisible(false);
     ESBrandName.disable();
     ESSupplierID.disable();
     ESSupplierName.disable();        
    }//GEN-LAST:event_ESItemIDActionPerformed

    private void ESBrandIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESBrandIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESBrandIDActionPerformed

    private void ESSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESSupplierIDActionPerformed

    private void ESItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESItemNameActionPerformed

    private void ESBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESBrandNameActionPerformed

    private void ESSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESSupplierNameActionPerformed

    private void ExpireSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpireSearchActionPerformed
        //    public void tableload()
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");

        Date d1=null;
        Date d2=null;

        try {

            d1=format.parse(format.format(FromExpire.getDate()));
            d2=format.parse(format.format(ToExpire.getDate()));

            long diff=d2.getTime()-d1.getTime();

            //long hours=diff/(60*60*1000);
            //long days=hours/24;

            if(diff<0){

                JOptionPane.showMessageDialog(null,"End date Should be Upcomming Date");
                //FromExpire.setDate(null);
                ToExpire.setDate(null);
            }
            else{
                tableloadA();
            }
        }
        catch(Exception e)
        {

        }

    }//GEN-LAST:event_ExpireSearchActionPerformed

    private void ESItemIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESItemIDKeyReleased
 try{
             clearExpireBrand();
             clearExpireSupplier();
             
       
       
       ESBrandID.setEditable(false);
       ESBrandName.setEditable(false);
       ESSupplierID.setEditable(false);
       ESSupplierName.setEditable(false);
     
       
       String sql="Select * from Expired_Item where ItemId Like '%"+ESItemID.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }        
    }//GEN-LAST:event_ESItemIDKeyReleased

    private void ToExpireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ToExpireKeyReleased
      
    }//GEN-LAST:event_ToExpireKeyReleased

    private void ERefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERefeshActionPerformed
      enable();
      tableload1();
      clearExpireItem();
      clearExpireBrand();
      clearExpireSupplier();
      
    }//GEN-LAST:event_ERefeshActionPerformed

    private void ESItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESItemNameKeyReleased
         try{
            
             clearExpireBrand();
             clearExpireSupplier();
             
       ESBrandID.setEditable(false);
       ESBrandName.setEditable(false);
       ESSupplierID.setEditable(false);
       ESSupplierName.setEditable(false);
       
       String sql="Select * from Expired_Item where ItemName Like '%"+ESItemName.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_ESItemNameKeyReleased

    private void ESBrandIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESBrandIDKeyReleased
        try{
             clearExpireItem();
             clearExpireSupplier();
             
       ESItemID.setEditable(false);
       ESItemName.setEditable(false);
       ESSupplierID.setEditable(false);
       ESSupplierName.setEditable(false);
       
       String sql="Select * from Expired_Item where BrandId Like '%"+ESBrandID.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_ESBrandIDKeyReleased

    private void ESBrandNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESBrandNameKeyReleased
         try{
             clearExpireItem();
             clearExpireSupplier();
             
       ESItemID.setEditable(false);
       ESItemName.setEditable(false);
       ESSupplierID.setEditable(false);
       ESSupplierName.setEditable(false);
       
       String sql="Select * from Expired_Item where BrandName Like '%"+ESBrandName.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_ESBrandNameKeyReleased

    private void ESSupplierIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESSupplierIDKeyReleased
        try{
            
             clearExpireItem();
             clearExpireBrand();
             
       ESItemID.setEditable(false);
       ESItemName.setEditable(false);
       ESBrandID.setEditable(false);
       ESBrandName.setEditable(false);
       
       String sql="Select * from Expired_Item where SupplierID Like '%"+ESSupplierID.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_ESSupplierIDKeyReleased

    private void ESSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ESSupplierNameKeyReleased
        try{
               clearExpireItem();
             clearExpireBrand();
             
       ESItemID.setEditable(false);
       ESItemName.setEditable(false);
       ESBrandID.setEditable(false);
       ESBrandName.setEditable(false);
            
       String sql="Select * from Expired_Item where SupplierName Like '%"+ESSupplierName.getText()+"%'";
       
            pst=conn.prepareStatement(sql);
          
            rs=pst.executeQuery();
            TableExpire.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_ESSupplierNameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String report = ".\\expireedItem.jrxml";
                        JasperDesign jd = JRXmlLoader.load(report);
                        String sql1 = "select * from Expired_Item";
                        JRDesignQuery n = new JRDesignQuery();
                        n.setText(sql1);
                        jd.setQuery(n);
                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                        JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int r=-1;
        r = TableExpire.getSelectedRow();       
               
        if(r==-1){
            JOptionPane.showMessageDialog(null,"Please choose a field first!","No Input", JOptionPane.INFORMATION_MESSAGE);

            return;
        }
        String ID = TableExpire.getValueAt(r, 0).toString();
        
        try{
        String report = ".\\expireedItem.jrxml";
                        JasperDesign jd = JRXmlLoader.load(report);
                        String sql1 = "select * from Expired_Item where itemid='" + ID+ "'";
                        JRDesignQuery n = new JRDesignQuery();
                        n.setText(sql1);
                        jd.setQuery(n);
                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                        JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ERefesh;
    private javax.swing.JTextField ESBrandID;
    private javax.swing.JTextField ESBrandName;
    private javax.swing.JTextField ESItemID;
    private javax.swing.JTextField ESItemName;
    private javax.swing.JTextField ESSupplierID;
    private javax.swing.JTextField ESSupplierName;
    private javax.swing.JButton ExpireSearch;
    private com.toedter.calendar.JDateChooser FromExpire;
    private javax.swing.JTable NearExpire;
    private javax.swing.JTable TableExpire;
    private com.toedter.calendar.JDateChooser ToExpire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
