/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agency;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author chath
 */
public class StoreManagement extends javax.swing.JInternalFrame {

    
    
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement s = null;
    
    
    
    
    public StoreManagement() {
        initComponents();
        conn = DBconnection.DBconnect.connectDb();
       // JCal.setVisible(false);
        generateID();
        //load Table
        
        tableLoad();
        
        
    }
    
    public void generateID(){

        try{
            s = conn.createStatement();
            rs = s.executeQuery("SELECT MAX(id) AS storeid FROM store");
           
            String storeid;
            
            while(rs.next()){
                
                storeid = rs.getString("storeid");
                String sid[] = storeid.split("ST");
                int no=Integer.parseInt(sid[1]);
                no = no + 1;
                TXTid.setText("ST"+no);

            }
        }
        
        catch (Exception e) {
            
            System.out.println(e);
        
        }
        
        finally{
        
            try{
            
                rs.close();
                
            
            }
            
            catch(Exception e){
        
                System.out.println(e);
        
            }
        
        }
    }
    
     public void clear(){
    
            //CLEAR ALL TEXT FIELDS
        
        TXTid.setText("");
        TXTname.setText("");
        buttonGroup1.clearSelection();
        TXTAaddress.setText("");
        TXTcon.setText("");
        generateID();
     }
    /**
     *
     */
    public void tableLoad()
    {
    
        try{
        
            String sql = "SELECT id,name,address,contact,productCategory FROM store";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
         
            storetable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        
        catch(Exception e){
        
            System.out.println(e);
        
        }
        
        finally{
        
            try{
            
                pst.close();
                rs.close();
                
            
            }
            
            catch(Exception e){
        
                System.out.println(e);
        
        }
        
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXTname = new javax.swing.JTextField();
        TXTcon = new javax.swing.JTextField();
        TXTid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTAaddress = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        RDBfert = new javax.swing.JRadioButton();
        RDBwater = new javax.swing.JRadioButton();
        RDBcement = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        storetable = new javax.swing.JTable();
        BTNinsert = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        BTNupdate = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setForeground(new java.awt.Color(102, 51, 255));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Store Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Store ID             ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Store Name         ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Address    ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Contact Number   ");

        TXTname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnameActionPerformed(evt);
            }
        });
        TXTname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnameKeyTyped(evt);
            }
        });

        TXTcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTconKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTconKeyTyped(evt);
            }
        });

        TXTid.setEditable(false);
        TXTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidActionPerformed(evt);
            }
        });

        TXTAaddress.setColumns(20);
        TXTAaddress.setRows(5);
        TXTAaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTAaddressKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TXTAaddress);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTcon)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTname)
                            .addComponent(TXTid))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TXTname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TXTcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Products              ");

        buttonGroup1.add(RDBfert);
        RDBfert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RDBfert.setText("Fertilizers");
        RDBfert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDBfertActionPerformed(evt);
            }
        });

        buttonGroup1.add(RDBwater);
        RDBwater.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RDBwater.setText("Water Tanks");
        RDBwater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDBwaterActionPerformed(evt);
            }
        });

        buttonGroup1.add(RDBcement);
        RDBcement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RDBcement.setText("Cement");
        RDBcement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDBcementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDBfert)
                    .addComponent(RDBwater)
                    .addComponent(RDBcement))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(RDBfert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RDBwater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RDBcement))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        storetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        storetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(storetable);

        BTNinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTNinsert.setText("Insert");
        BTNinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinsertActionPerformed(evt);
            }
        });

        BTNdelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTNdelete.setText("Delete");
        BTNdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeleteActionPerformed(evt);
            }
        });

        BTNupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTNupdate.setText("Update");
        BTNupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNupdateActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Store Management");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTNinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(BTNdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(BTNupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(297, 297, 297))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinsertActionPerformed
        if(TXTid.getText().equals("") || TXTname.getText().equals("") || TXTAaddress.getText().equals("") || TXTcon.getText().equals("") || buttonGroup1.isSelected(null))
        {

            JOptionPane.showMessageDialog(null,"All fields are required to be filled");

        }
       
        
            
        else{
        
        String stname = TXTname.getText();
        String stid = TXTid.getText();
        String stadd = TXTAaddress .getText();
        String stcontact = TXTcon.getText();
        String stproduct = Product;
        
        
        
        String q = "INSERT INTO store (id,name,address,contact,productCategory) values('"+ stid +"' , '"+ stname +"' , '"+ stadd +"' , '"+ stcontact +"' , '"+ stproduct +"')";

         try
        {
            
                pst = conn.prepareStatement(q);
                pst.execute();
                
                //load Table
                tableLoad();
                clear();
                
                
        }

        catch(Exception e)
        {

            System.out.println(e);

        }
         
         finally{
        
            try{
            
                pst.close();
                
            
            }
            
            catch(Exception e){
        
                System.out.println(e);
        
        }
        
        }
                    
        
        }
    }//GEN-LAST:event_BTNinsertActionPerformed

    private void RDBfertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDBfertActionPerformed
        Product = "F";
    }//GEN-LAST:event_RDBfertActionPerformed

    private void RDBwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDBwaterActionPerformed
        Product = "W";
    }//GEN-LAST:event_RDBwaterActionPerformed

    private void RDBcementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDBcementActionPerformed
        Product = "C";
    }//GEN-LAST:event_RDBcementActionPerformed

    private void BTNdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeleteActionPerformed
        int y = JOptionPane.showConfirmDialog(null,"Do you really want to delete this record?");

        if(y==0)
        {

            String id = TXTid.getText();

            String sql = "DELETE from STORE where id = '"+ id +"'";

            currentStoreNumber--;
            
            try
            {

                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record was successfully removed");
                clear();
                
                //load Table
                tableLoad();

            }

            catch(Exception e)
            {
                    System.out.println("line 413");
            }
            
            finally{
        
            try{
            
                pst.close();
               
            
            }
            
            catch(Exception e){
        
                System.out.println(e);
        
        }
        
        }
            
        }
    }//GEN-LAST:event_BTNdeleteActionPerformed

    private void storetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storetableMouseClicked
        int row = storetable.getSelectedRow();
        String stid = storetable.getValueAt(row,0).toString();
        String stname = storetable.getValueAt(row,1).toString();
        String stadd = storetable.getValueAt(row,2).toString();
        String stcon = storetable.getValueAt(row,3).toString();
        String stproduct = storetable.getValueAt(row,4).toString();
        
        TXTid.setText(stid);
        TXTname.setText(stname);
        TXTAaddress.setText(stadd);
        TXTcon.setText(stcon);
        
        if (stproduct.equals("F"))
        {
            RDBfert.setSelected(true);
        }
        else if (stproduct.equals("W"))
        {
            RDBwater.setSelected(true);
        }
        else 
        {
            RDBcement.setSelected(true);
        }
        
    }//GEN-LAST:event_storetableMouseClicked

    private void BTNupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNupdateActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update this record?");

        if(x == 0)
        {

        String stname = TXTname.getText();
        String stid = TXTid.getText();
        String stadd = TXTAaddress.getText();
        String stcontact = TXTcon.getText();
        String stproduct = Product;

            String sql = "UPDATE store SET name='"+ stname +"' , id='"+ stid +"' ,  address='"+ stadd +"' , contact='"+ stcontact +"' ,  productCategory='"+ stproduct +"'    WHERE id = '"+ stid +"'";

            try{

                
                
                    pst = conn.prepareStatement(sql);
                    pst.execute();

                

                //load Table
                tableLoad();

            }

            catch(Exception e){
                    System.out.println(e);
            }
            
            finally{
        
            try{
            
                pst.close();
                
            
            }
            
            catch(Exception e){
        
                System.out.println(e);
        
        }
        
        }

        }
    }//GEN-LAST:event_BTNupdateActionPerformed

    private void TXTnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnameActionPerformed
        
        TXTAaddress.requestFocus();
        
    }//GEN-LAST:event_TXTnameActionPerformed

    private void TXTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidActionPerformed

    private void TXTAaddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTAaddressKeyTyped
        
    }//GEN-LAST:event_TXTAaddressKeyTyped

    private void TXTconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTconKeyPressed
        TXTcon.requestFocus();
    }//GEN-LAST:event_TXTconKeyPressed

    private void TXTnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnameKeyTyped
        
        
        char c=evt.getKeyChar();

        if(Character.isDigit(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Letters");
        }
        
        
    }//GEN-LAST:event_TXTnameKeyTyped

    private void TXTconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTconKeyTyped
        char c=evt.getKeyChar();

        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Enter only Numbers");
        }
    }//GEN-LAST:event_TXTconKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNinsert;
    private javax.swing.JButton BTNupdate;
    private javax.swing.JRadioButton RDBcement;
    private javax.swing.JRadioButton RDBfert;
    private javax.swing.JRadioButton RDBwater;
    private javax.swing.JTextArea TXTAaddress;
    private javax.swing.JTextField TXTcon;
    private javax.swing.JTextField TXTid;
    private javax.swing.JTextField TXTname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable storetable;
    // End of variables declaration//GEN-END:variables
private String Product;
private String GenID;
public static int currentStoreNumber;
}
