/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Asset;

/**
 *
 * @author User
 */
import DBconnection.DBconnect;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AccumulatedDepreciation extends javax.swing.JInternalFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement ps = null;
    /**
     * Creates new form AccumulatedDepreciation
     */
    public AccumulatedDepreciation() {
        initComponents();
        conn=DBconnect.connectDb();
        calendar();
        showtime();
    }

    int month,day,year,hour,minute,second;
    
     public void calendar()
    {
    
        Calendar cal=new GregorianCalendar();
        year= cal.get(Calendar.YEAR);
        month=cal.get(Calendar.MONTH)+1;
        day=cal.get(Calendar.DAY_OF_MONTH);
//        lbl_date.setText(year+"/"+month+"/"+day);
//        lbl_date1.setText(year+"/"+month+"/"+day);
        
    }
    
    public void showtime(){
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Calendar cal = new GregorianCalendar();
                hour = cal.get(Calendar.HOUR);
                minute = cal.get(Calendar.MINUTE);
                second = cal.get(Calendar.SECOND);
               // lbl_time.setText(hour+":"+minute+":"+second); 
            }
        }).start();
                
    }
     
     public void clear(){
               txt_asset_id.setText("");
               txt_description.setText("");
               txt_net_book_value.setText("");
               txt_cost.setText("");
               txt_Rate.setText("");
               txt_life.setText("");
               ((JTextField)revalueDate.getDateEditor().getUiComponent()).setText("");
    }
     
    public void delete(){
               String sql = "delete from Depreciation where Asset_Id=?";
            try{
                ps=conn.prepareStatement(sql);
                ps.setString(1,txt_asset_id.getText());
                ps.execute();

           }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
           }
        
            finally{
            try{
                ps.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revaluation = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        txt_net_book_value = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_life = new javax.swing.JTextField();
        txt_cost = new javax.swing.JTextField();
        btn_change = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_Rate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        revalueDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txt_asset_id = new javax.swing.JTextField();
        btn_revalue_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        btn_Clr = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_assetId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Description = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_netBookValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_accumulated_depre = new javax.swing.JTextField();
        btn_revaluation = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_clr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        revaluation.setLocation(new java.awt.Point(365, 0));
        revaluation.setPreferredSize(new java.awt.Dimension(500, 750));
        revaluation.setSize(new java.awt.Dimension(1000, 725));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Net Book Value");

        txt_net_book_value.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_net_book_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_net_book_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_net_book_valueKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revaluation Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 22), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Value");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Depreciable Life");

        txt_life.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_life.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_life.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lifeKeyTyped(evt);
            }
        });

        txt_cost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_costKeyTyped(evt);
            }
        });

        btn_change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_change.setText("Change");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Depreciation rate");

        txt_Rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Rate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RateKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Revaluation Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_life)
                            .addComponent(txt_cost)
                            .addComponent(txt_Rate)
                            .addComponent(revalueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btn_change)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revalueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txt_Rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_life, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_change)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("AssetId");

        txt_asset_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_asset_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_revalue_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_revalue_search.setText("Search");
        btn_revalue_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revalue_searchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Asset Description");

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_description.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_Clr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Clr.setText("Clear");
        btn_Clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout revaluationLayout = new javax.swing.GroupLayout(revaluation.getContentPane());
        revaluation.getContentPane().setLayout(revaluationLayout);
        revaluationLayout.setHorizontalGroup(
            revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revaluationLayout.createSequentialGroup()
                .addGroup(revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_asset_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(txt_net_book_value, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btn_revalue_search)
                        .addGap(60, 60, 60)
                        .addComponent(btn_Clr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        revaluationLayout.setVerticalGroup(
            revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revaluationLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_asset_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revaluationLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(txt_net_book_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(revaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_revalue_search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setPreferredSize(new java.awt.Dimension(1000, 705));

        jPanel1.setPreferredSize(new java.awt.Dimension(913, 675));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asset", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 22), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Asset Id");

        txt_assetId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_assetId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Asset Description");

        txt_Description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Description.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Net Book Value");

        txt_netBookValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_netBookValue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_netBookValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_netBookValueKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Accumulated Depreciation");

        txt_accumulated_depre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_accumulated_depre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_accumulated_depre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_accumulated_depreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_accumulated_depre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_netBookValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_assetId)
                        .addComponent(txt_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_assetId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_netBookValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_accumulated_depre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btn_revaluation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_revaluation.setText("Revaluation");
        btn_revaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revaluationActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_clr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clr.setText("Clear");
        btn_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_revaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_revaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("   Accumulated Depreciation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_revaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revaluationActionPerformed
        revaluation.setVisible(true);
    }//GEN-LAST:event_btn_revaluationActionPerformed
                                    

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try{
       
       String sql="Select a.Asset_Id,a.Asset_Description,d.Net_Book_Value from Asset a,Depreciation d where a.Asset_Id Like '%"+txt_assetId.getText()+"%' AND a.Asset_Description Like '%"+txt_Description.getText()+"%' AND a.Asset_Id=d.Asset_Id";
    
            ps=conn.prepareStatement(sql);
            
            rs=ps.executeQuery();
          
         if(rs.next()){
            txt_assetId.setText(rs.getString("Asset_Id"));
            txt_Description.setText(rs.getString("Asset_Description"));
            txt_netBookValue.setText(rs.getString("Net_Book_Value"));
         }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                ps.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_accumulated_depreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_accumulated_depreMouseClicked
         try{
       
            String sql="Select d.Depreciable_Value,a.Purchased_Date from Asset a,Depreciation d where a.Asset_Id Like '%"+txt_assetId.getText()+"%' AND a.Asset_Description Like '%"+txt_Description.getText()+"%' AND a.Asset_Id=d.Asset_Id";
       
            ps=conn.prepareStatement(sql);
            
            rs=ps.executeQuery();
           
            Double Depre_Value = Double.parseDouble(rs.getString("Depreciable_Value"));
            String Date = rs.getString("Purchased_Date");
		
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat df = new SimpleDateFormat("yyyy");

            java.util.Date d1 = null;
            int diff = 0;
            
            d1 = format.parse(Date);
            String year1 = df.format(d1);
            diff = year - Integer.parseInt(year1);
            
            String val = Double.toString(Depre_Value*diff);
            
            txt_accumulated_depre.setText(val);
  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
         
         finally{
            try{
                ps.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_txt_accumulated_depreMouseClicked

    private void btn_revalue_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revalue_searchActionPerformed
        try{
       
       String sql="Select a.Asset_Id,a.Asset_Description,d.Net_Book_Value from Asset a,Depreciation d where a.Asset_Id Like '%"+txt_asset_id.getText()+"%' AND a.Asset_Description Like '%"+txt_description.getText()+"%' AND a.Asset_Id=d.Asset_Id";
       
            ps=conn.prepareStatement(sql);
            
            rs=ps.executeQuery();
           
            txt_asset_id.setText(rs.getString("Asset_Id"));
            txt_description.setText(rs.getString("Asset_Description"));
            txt_net_book_value.setText(rs.getString("Net_Book_Value"));
  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Asset should be existing depreciated asset");
        }
        
        finally{
            try{
                ps.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btn_revalue_searchActionPerformed

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
       
    if(txt_asset_id.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Enter the Asset Id that is to be revalued");
    }
    else if(((JTextField)revalueDate.getDateEditor().getUiComponent()).getText().isEmpty())
    {
        JOptionPane.showConfirmDialog(rootPane, "Enter the date", "Error", JOptionPane.ERROR_MESSAGE);
    }
    else if(txt_cost.getText().isEmpty())
    {
        JOptionPane.showConfirmDialog(rootPane, "Enter the value of the asset", "Error", JOptionPane.ERROR_MESSAGE);
    }
    else{
        try{
          
            String val1 = txt_cost.getText();
            String val2 = txt_Rate.getText();
            String val3 = txt_life.getText();
            String val4 = ((JTextField)revalueDate.getDateEditor().getUiComponent()).getText();
          
            String sql = "Update Asset set Purchased_Cost='"+val1+"',Depreciation_Rate='"+val2+"',Depreciable_Life='"+val3+"',Purchased_Date='"+val4+"' where Asset_Id=?";
            
            ps=conn.prepareStatement(sql);
            ps.setString(1,txt_asset_id.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null,"Updated");
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally{
            try{
                ps.close();
                rs.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        delete();
        clear();
    }
    }//GEN-LAST:event_btn_changeActionPerformed

    private void btn_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clrActionPerformed
        
                txt_assetId.setText("");
                txt_Description.setText("");
                txt_netBookValue.setText("");
                txt_accumulated_depre.setText("");
               
    }//GEN-LAST:event_btn_clrActionPerformed

    private void btn_ClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClrActionPerformed
                txt_asset_id.setText("");
                txt_description.setText("");
                txt_net_book_value.setText("");
    }//GEN-LAST:event_btn_ClrActionPerformed

    private void txt_netBookValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_netBookValueKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Only numbers are allowed");
        }
    }//GEN-LAST:event_txt_netBookValueKeyTyped

    private void txt_net_book_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_net_book_valueKeyTyped
       char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Only numbers are allowed");
        }
    }//GEN-LAST:event_txt_net_book_valueKeyTyped

    private void txt_costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Only numbers are allowed");
        }
    }//GEN-LAST:event_txt_costKeyTyped

    private void txt_RateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RateKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Only numbers are allowed");
        }
    }//GEN-LAST:event_txt_RateKeyTyped

    private void txt_lifeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lifeKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Only numbers are allowed");
        }
    }//GEN-LAST:event_txt_lifeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clr;
    private javax.swing.JButton btn_change;
    private javax.swing.JButton btn_clr;
    private javax.swing.JButton btn_revaluation;
    private javax.swing.JButton btn_revalue_search;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JDialog revaluation;
    private com.toedter.calendar.JDateChooser revalueDate;
    private javax.swing.JTextField txt_Description;
    private javax.swing.JTextField txt_Rate;
    private javax.swing.JTextField txt_accumulated_depre;
    private javax.swing.JTextField txt_assetId;
    private javax.swing.JTextField txt_asset_id;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_life;
    private javax.swing.JTextField txt_netBookValue;
    private javax.swing.JTextField txt_net_book_value;
    // End of variables declaration//GEN-END:variables
}
