/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import DBconnection.DBconnect;
import DBclass.me;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author DELL-PC
 */
public class viewResigned extends javax.swing.JInternalFrame {
    
       String s;
       Connection  conn = null;
       PreparedStatement pst = null,pst1=null;
       ResultSet rs = null,rs1=null;
       byte[] person_image = null;
       byte [] ss;
       String selectedb=null;
       

    /**
     * Creates new form addEmployee
     */
    public viewResigned() {
        
        initComponents();
        
        conn=DBconnect.connectDb();
     
        
    }
    
    
    
    void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d=new Date();
                SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }
        }).start();
    }
    
 
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datevalid = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        nic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1218, 685));
        getContentPane().setLayout(null);
        getContentPane().add(datevalid);
        datevalid.setBounds(850, 70, 50, 40);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Resigned Employees");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(10, 0, 480, 44);

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel9.add(time);
        time.setBounds(1025, 0, 130, 50);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 1160, 50);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 200, 1120, 440);
        getContentPane().add(nic);
        nic.setBounds(160, 100, 180, 30);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 140, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIC       :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 90, 30);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 350, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
               
               if(me.nicCheck(nic.getText()))
               {
               String sql = "SELECT employee_id,first_name,last_name,username,language,birth_day,age,nic_no,address,phone_no,designation,status,addded_date, total_epf,total_etf,Bonus,gratuity_payment,resigned_date FROM Resigned_Employees where nic_no = '"+nic.getText()+"'";
               pst = conn.prepareStatement(sql);
               rs=pst.executeQuery();
               
               jTable2.setModel(DbUtils.resultSetToTableModel(rs));
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Invalid NIC");
               }
               } catch (SQLException ex) {
                   
                   
               ex.printStackTrace();
           }finally{
               try {
                   pst.close();
                   rs.close();
               } catch (Exception e) {
               }
           }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datevalid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
