/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import DBconnection.DBconnect;
import DBclass.me;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author DELL-PC
 */
public class viewSalaryReport extends javax.swing.JInternalFrame {
    
       String s;
       Connection  conn = null;
       PreparedStatement pst = null,pst1=null;
       ResultSet rs = null,rs1=null;
       byte[] person_image = null;
       byte [] ss;
       String selectedb=null;
       
       String DD1,DD2;

    /**
     * Creates new form addEmployee
     */
    public viewSalaryReport() {
        
        initComponents();
        
        conn=DBconnect.connectDb();
     
        
    }
    
    
    
    void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d=new Date();
                SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }
        }).start();
    }
    
 
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datevalid = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        vfrom = new com.toedter.calendar.JDateChooser();
        vto = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1218, 685));
        getContentPane().setLayout(null);
        getContentPane().add(datevalid);
        datevalid.setBounds(850, 70, 50, 40);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Salary Report");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(10, 0, 380, 44);

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel9.add(time);
        time.setBounds(1025, 0, 130, 50);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 1160, 50);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(390, 70, 750, 250);

        vfrom.setDateFormatString("MM dd, yyyy");
        getContentPane().add(vfrom);
        vfrom.setBounds(60, 90, 130, 30);

        vto.setDateFormatString("MM dd, yyyy");
        vto.setEnabled(false);
        getContentPane().add(vto);
        vto.setBounds(240, 90, 130, 30);

        jButton5.setText("Show report for a given employee");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 270, 310, 30);
        getContentPane().add(id);
        id.setBounds(60, 230, 100, 30);

        jButton6.setText("Show report for all employees");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 170, 310, 30);

        jButton1.setText("Set Date Range");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 130, 130, 30);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 350, 250);

        jButton2.setText("Generate Salary Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 340, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
           try {
               String D1 =((JTextField)vfrom.getDateEditor().getUiComponent()).getText();
               String D2 = ((JTextField)vto.getDateEditor().getUiComponent()).getText();
               
               DD1=D1;
               DD2=D2;
               
               String sql2 = "SELECT * FROM Salary where Date BETWEEN '"+D1+"' AND '"+D2+"'";
               pst1 = conn.prepareStatement(sql2);
               rs1 = pst1.executeQuery();
               
               jTable2.setModel(DbUtils.resultSetToTableModel(rs1));
           } catch (SQLException ex) {
               Logger.getLogger(viewSalaryReport.class.getName()).log(Level.SEVERE, null, ex);
           }finally
           {
               try {
                   pst1.close();
                   rs1.close();
                   
               } catch (Exception e) {
               }
           }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("MM dd, yyyy");
            SimpleDateFormat dy = new SimpleDateFormat("yyyy");
            SimpleDateFormat dm = new SimpleDateFormat("MM");
            SimpleDateFormat dd = new SimpleDateFormat("dd");

            java.util.Date d1 = null;
            

	try{
	    
		String date =((JTextField)vfrom.getDateEditor().getUiComponent()).getText();
              
                    d1 = format.parse(date);
                    int year1 = Integer.parseInt(dy.format(d1));
                    int month1 = Integer.parseInt(dm.format(d1));
                    int day1= Integer.parseInt(dd.format(d1));

                  if(month1+1<10)
                  {
		((JTextField)vto.getDateEditor().getUiComponent()).setText("0"+(month1+1)+" "+day1+", "+year1);
                  }
                  else
                  {
		((JTextField)vto.getDateEditor().getUiComponent()).setText((month1+1)+" "+day1+", "+year1);
                  }
                  
                  
                    }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(id.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"ID Required");
        }
        else
        {
        try {
               String D1 =((JTextField)vfrom.getDateEditor().getUiComponent()).getText();
               String D2 = ((JTextField)vto.getDateEditor().getUiComponent()).getText();
               
               
               String sql2 = "SELECT * FROM Salary where Date BETWEEN '"+D1+"' AND '"+D2+"' AND employee_id = '"+id.getText()+"'";
               pst1 = conn.prepareStatement(sql2);
               rs1 = pst1.executeQuery();
               
               jTable2.setModel(DbUtils.resultSetToTableModel(rs1));
           } catch (SQLException ex) {
               Logger.getLogger(viewSalaryReport.class.getName()).log(Level.SEVERE, null, ex);
           }
            finally{
            try {
                pst1.close();
                rs1.close();
                
            } catch (Exception e) {
            }
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        try{
        String report = ".\\salary.jrxml";
                        JasperDesign jd = JRXmlLoader.load(report);
                        String sql1 = "SELECT * FROM Salary where Date BETWEEN '"+DD1+"' AND '"+DD2+"' order by employee_id";
                        JRDesignQuery n = new JRDesignQuery();
                        n.setText(sql1);
                        jd.setQuery(n);
                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                        JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datevalid;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel time;
    private com.toedter.calendar.JDateChooser vfrom;
    private com.toedter.calendar.JDateChooser vto;
    // End of variables declaration//GEN-END:variables
}
